from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Text, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import os

# Get database URL from environment or use SQLite as default
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./fitflow.db")

# Create engine with appropriate settings for SQLite
engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
)

# Create session factory
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Base class for all models
Base = declarative_base()


# ==========================================
# DATABASE MODELS
# ==========================================

class User(Base):
    """
    User model for storing user profile information.
    
    Attributes:
        id: Primary key
        user_id: Unique user identifier (e.g., "alice")
        name: User's full name
        age: User's age in years
        weight_kg: Current weight in kilograms
        height_cm: Height in centimeters
        fitness_level: beginner, intermediate, advanced
        goal: muscle_gain, fat_loss, strength, endurance
        equipment: List of available equipment
        created_at: Account creation timestamp
    
    Example:
        {
            "user_id": "alice",
            "name": "Alice Smith",
            "age": 28,
            "weight_kg": 65,
            "height_cm": 165,
            "fitness_level": "intermediate",
            "goal": "muscle_gain",
            "equipment": ["dumbbells", "barbell"]
        }
    """
    
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    age = Column(Integer, nullable=False)
    weight_kg = Column(Float, nullable=False)
    height_cm = Column(Integer, nullable=False)
    fitness_level = Column(String, nullable=False)
    goal = Column(String, nullable=False)
    equipment = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<User {self.user_id}: {self.name}>"
    
    def __str__(self):
        return f"{self.name} ({self.user_id}) - {self.fitness_level} - Goal: {self.goal}"


class Metric(Base):
    """
    Metric model for storing user performance metrics.
    
    Tracks daily/weekly fitness metrics for progress analysis.
    
    Attributes:
        id: Primary key
        user_id: Foreign key to user
        weight_kg: Body weight in kilograms
        strength_1rm: Maximum strength (1 rep max) in kg
        sleep_hours: Hours of sleep (0-24)
        mood: Mood score (1-10)
        energy: Energy level (1-10)
        created_at: Timestamp when metric was logged
    
    Example:
        {
            "user_id": "alice",
            "weight_kg": 65.5,
            "strength_1rm": 185,
            "sleep_hours": 7.5,
            "mood": 8,
            "energy": 8
        }
    """
    
    __tablename__ = "metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True, nullable=False)
    weight_kg = Column(Float, nullable=False)
    strength_1rm = Column(Float, nullable=False)
    sleep_hours = Column(Float, nullable=False)
    mood = Column(Integer, nullable=False)
    energy = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<Metric {self.user_id}: {self.weight_kg}kg, {self.strength_1rm}kg>"
    
    def __str__(self):
        return f"Weight: {self.weight_kg}kg | Strength: {self.strength_1rm}kg | Sleep: {self.sleep_hours}h | Mood: {self.mood}/10"


class Plan(Base):
    """
    Plan model for storing generated fitness plans.
    
    Stores complete personalized fitness plans generated by the orchestrator.
    
    Attributes:
        id: Primary key
        plan_id: Unique plan identifier (UUID-like)
        user_id: Foreign key to user
        week: Week number (1-52) for the plan
        plan_data: Complete plan data as JSON (workout, nutrition, coaching, etc)
        created_at: Timestamp when plan was generated
    
    Example:
        {
            "plan_id": "plan_1704516124.5678",
            "user_id": "alice",
            "week": 1,
            "plan_data": {
                "workout_plan": {...},
                "nutrition_plan": {...},
                "coaching_plan": {...}
            }
        }
    """
    
    __tablename__ = "plans"
    
    id = Column(Integer, primary_key=True, index=True)
    plan_id = Column(String, unique=True, index=True, nullable=False)
    user_id = Column(String, index=True, nullable=False)
    week = Column(Integer, nullable=False)
    plan_data = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<Plan {self.plan_id}: Week {self.week} for {self.user_id}>"
    
    def __str__(self):
        return f"Plan {self.plan_id} - Week {self.week}"


class ChatMessage(Base):
    """
    ChatMessage model for storing user-coach conversations.
    
    Stores all conversations between user and AI coaching agent.
    
    Attributes:
        id: Primary key
        user_id: Foreign key to user
        user_message: Message from user
        bot_response: Response from coaching agent
        created_at: Timestamp of message
    
    Example:
        {
            "user_id": "alice",
            "user_message": "How can I improve my gains?",
            "bot_response": "Based on your muscle_gain goal, here's my advice..."
        }
    """
    
    __tablename__ = "chat_messages"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True, nullable=False)
    user_message = Column(Text, nullable=False)
    bot_response = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<ChatMessage {self.id}: {self.user_id}>"
    
    def __str__(self):
        return f"Chat #{self.id} | User: {self.user_message[:30]}... | Bot: {self.bot_response[:30]}..."


# ==========================================
# DATABASE INITIALIZATION
# ==========================================

def init_db():
    """
    Initialize database by creating all tables.
    
    Creates:
    - users table
    - metrics table
    - plans table
    - chat_messages table
    
    Call this on app startup to ensure all tables exist.
    """
    Base.metadata.create_all(bind=engine)


# Create all tables on import
Base.metadata.create_all(bind=engine)


# ==========================================
# DATABASE SESSION MANAGEMENT
# ==========================================

def get_db():
    """
    Dependency for getting database session.
    
    Used with FastAPI's Depends() to inject database session into endpoints.
    
    Usage:
        @app.get("/users/{user_id}")
        def get_user(user_id: str, db: Session = Depends(get_db)):
            user = db.query(User).filter(User.user_id == user_id).first()
            return user
    
    Yields:
        Database session
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ==========================================
# DATABASE HELPER FUNCTIONS
# ==========================================

def get_session():
    """
    Get a database session (alternative to get_db).
    
    Use when not in FastAPI context.
    
    Returns:
        Database session that must be closed manually
    
    Usage:
        db = get_session()
        try:
            user = db.query(User).filter(User.user_id == "alice").first()
        finally:
            db.close()
    """
    return SessionLocal()


def reset_db():
    """
    Drop all tables and recreate them.
    
    WARNING: This will delete all data!
    
    Use only for:
    - Testing
    - Development
    - Complete data reset
    
    Usage:
        reset_db()
        init_db()
    """
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)


# ==========================================
# DATABASE QUERY HELPERS
# ==========================================

def create_user(db, user_id: str, name: str, age: int, weight_kg: float, 
                height_cm: int, fitness_level: str, goal: str, equipment: list) -> User:
    """
    Create a new user in the database.
    
    Args:
        db: Database session
        user_id: Unique user identifier
        name: User's full name
        age: Age in years
        weight_kg: Weight in kg
        height_cm: Height in cm
        fitness_level: beginner/intermediate/advanced
        goal: muscle_gain/fat_loss/strength/endurance
        equipment: List of available equipment
    
    Returns:
        Created User object
    """
    user = User(
        user_id=user_id,
        name=name,
        age=age,
        weight_kg=weight_kg,
        height_cm=height_cm,
        fitness_level=fitness_level,
        goal=goal,
        equipment=equipment
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


def get_user(db, user_id: str) -> User:
    """
    Get user by user_id.
    
    Args:
        db: Database session
        user_id: User ID to search for
    
    Returns:
        User object or None if not found
    """
    return db.query(User).filter(User.user_id == user_id).first()


def get_all_users(db) -> list:
    """
    Get all users in database.
    
    Args:
        db: Database session
    
    Returns:
        List of all User objects
    """
    return db.query(User).all()


def delete_user(db, user_id: str) -> bool:
    """
    Delete user and all associated data.
    
    Deletes:
    - User profile
    - All metrics
    - All plans
    - All chat messages
    
    Args:
        db: Database session
        user_id: User ID to delete
    
    Returns:
        True if deleted, False if not found
    """
    user = db.query(User).filter(User.user_id == user_id).first()
    if not user:
        return False
    
    # Delete associated data
    db.query(Metric).filter(Metric.user_id == user_id).delete()
    db.query(Plan).filter(Plan.user_id == user_id).delete()
    db.query(ChatMessage).filter(ChatMessage.user_id == user_id).delete()
    
    # Delete user
    db.delete(user)
    db.commit()
    return True


def log_metric(db, user_id: str, weight_kg: float, strength_1rm: float, 
               sleep_hours: float, mood: int, energy: int) -> Metric:
    """
    Log a new metric for user.
    
    Args:
        db: Database session
        user_id: User ID
        weight_kg: Body weight in kg
        strength_1rm: 1RM strength in kg
        sleep_hours: Hours of sleep
        mood: Mood score (1-10)
        energy: Energy level (1-10)
    
    Returns:
        Created Metric object
    """
    metric = Metric(
        user_id=user_id,
        weight_kg=weight_kg,
        strength_1rm=strength_1rm,
        sleep_hours=sleep_hours,
        mood=mood,
        energy=energy
    )
    db.add(metric)
    db.commit()
    db.refresh(metric)
    return metric


def get_user_metrics(db, user_id: str, limit: int = None) -> list:
    """
    Get all metrics for a user.
    
    Args:
        db: Database session
        user_id: User ID
        limit: Maximum number of records to return
    
    Returns:
        List of Metric objects ordered by date
    """
    query = db.query(Metric).filter(Metric.user_id == user_id).order_by(Metric.created_at)
    if limit:
        query = query.limit(limit)
    return query.all()


def get_latest_metric(db, user_id: str) -> Metric:
    """
    Get most recent metric for user.
    
    Args:
        db: Database session
        user_id: User ID
    
    Returns:
        Most recent Metric object or None
    """
    return db.query(Metric).filter(Metric.user_id == user_id).order_by(
        Metric.created_at.desc()
    ).first()


def save_plan(db, plan_id: str, user_id: str, week: int, plan_data: dict) -> Plan:
    """
    Save a generated plan to database.
    
    Args:
        db: Database session
        plan_id: Unique plan ID
        user_id: User ID
        week: Week number (1-52)
        plan_data: Complete plan data as dict
    
    Returns:
        Created Plan object
    """
    plan = Plan(
        plan_id=plan_id,
        user_id=user_id,
        week=week,
        plan_data=plan_data
    )
    db.add(plan)
    db.commit()
    db.refresh(plan)
    return plan


def get_plan(db, plan_id: str) -> Plan:
    """
    Get plan by plan_id.
    
    Args:
        db: Database session
        plan_id: Plan ID
    
    Returns:
        Plan object or None
    """
    return db.query(Plan).filter(Plan.plan_id == plan_id).first()


def get_user_plans(db, user_id: str, limit: int = 10) -> list:
    """
    Get plans for user, most recent first.
    
    Args:
        db: Database session
        user_id: User ID
        limit: Maximum number of plans
    
    Returns:
        List of Plan objects
    """
    return db.query(Plan).filter(Plan.user_id == user_id).order_by(
        Plan.created_at.desc()
    ).limit(limit).all()


def get_current_plan(db, user_id: str) -> Plan:
    """
    Get current (most recent) plan for user.
    
    Args:
        db: Database session
        user_id: User ID
    
    Returns:
        Most recent Plan object or None
    """
    return db.query(Plan).filter(Plan.user_id == user_id).order_by(
        Plan.created_at.desc()
    ).first()


def save_chat_message(db, user_id: str, user_message: str, bot_response: str) -> ChatMessage:
    """
    Save chat message exchange to database.
    
    Args:
        db: Database session
        user_id: User ID
        user_message: Message from user
        bot_response: Response from bot/coach
    
    Returns:
        Created ChatMessage object
    """
    message = ChatMessage(
        user_id=user_id,
        user_message=user_message,
        bot_response=bot_response
    )
    db.add(message)
    db.commit()
    db.refresh(message)
    return message


def get_chat_history(db, user_id: str, limit: int = 20) -> list:
    """
    Get chat history for user.
    
    Args:
        db: Database session
        user_id: User ID
        limit: Maximum number of messages
    
    Returns:
        List of ChatMessage objects, most recent first
    """
    return db.query(ChatMessage).filter(ChatMessage.user_id == user_id).order_by(
        ChatMessage.created_at.desc()
    ).limit(limit).all()


# ==========================================
# DATABASE STATISTICS
# ==========================================

def get_db_stats(db) -> dict:
    """
    Get database statistics.
    
    Returns:
        Dict with counts of all records
    
    Usage:
        stats = get_db_stats(db)
        print(f"Users: {stats['users']}")
    """
    return {
        "users": db.query(User).count(),
        "metrics": db.query(Metric).count(),
        "plans": db.query(Plan).count(),
        "chat_messages": db.query(ChatMessage).count()
    }


def print_db_info():
    """
    Print database information and connection details.
    
    Useful for debugging and verification.
    """
    print("\n" + "="*50)
    print("FitFlow Database Information")
    print("="*50)
    print(f"Database URL: {DATABASE_URL}")
    print(f"Database Type: {'SQLite' if 'sqlite' in DATABASE_URL else 'PostgreSQL'}")
    print("\nTables:")
    print("  - users (User profiles)")
    print("  - metrics (Performance metrics)")
    print("  - plans (Generated plans)")
    print("  - chat_messages (Coaching conversations)")
    print("\nModels:")
    print(f"  - User: {User.__doc__.split(chr(10)).strip()}")
    print(f"  - Metric: {Metric.__doc__.split(chr(10)).strip()}")
    print(f"  - Plan: {Plan.__doc__.split(chr(10)).strip()}")
    print(f"  - ChatMessage: {ChatMessage.__doc__.split(chr(10)).strip()}")
    print("\nFunctions:")
    print("  - init_db(): Create all tables")
    print("  - reset_db(): Clear all data")
    print("  - get_db(): FastAPI dependency")
    print("  - get_session(): Manual session")
    print("="*50 + "\n")
